Chore: elements
nikkoabucejo/clode pull request #20
Opened 2024-02-15 11:55 UTC by jazztinecruz

- [ ] Button
- [ ] Language
- [ ] Typography
- [ ] Icon
- [ ] User
- [ ] Added font-headliner
- [ ] Added radius-base

2024-02-15 12:23 UTC, nikkoabucejo requested changes
Please see comments

2024-02-15 12:23 UTC, nikkoabucejo commented on core/components/icon/index.tsx
> +  Svg: React.ForwardRefExoticComponent<
Can we rename this to `Element`

2024-02-15 12:23 UTC, nikkoabucejo commented on core/components/language/index.tsx
> +"use client";
This is suppose to be server component

2024-02-15 12:23 UTC, nikkoabucejo commented on core/components/button/index.tsx
I don't we need button component anymore

2024-02-15 12:23 UTC, nikkoabucejo commented on core/components/typography/index.tsx
> +"use client";
Make this as server component

2024-02-15 12:23 UTC, nikkoabucejo commented on core/components/typography/index.tsx
> +  children: ReactNode;
We have type `Children` globally

2024-02-15 12:23 UTC, nikkoabucejo commented on core/components/language/index.tsx
> +  children: ReactNode;
We have Children type globally

2024-02-15 12:23 UTC, nikkoabucejo commented on core/components/typography/index.tsx
> +const Typography = ({ heading = "body", children, className = "" }: Props) => {
Remove the `Body` this will cause errors on Hydration, I think we should default span tag

2024-02-16 10:17 UTC, jazztinecruz commented on core/components/typography/index.tsx
> +const Typography = ({ heading = "body", children, className = "" }: Props) => {
I renamed the Body to Base. but I think p tag is the right default.

2024-02-16 10:18 UTC, jazztinecruz commented on core/components/language/index.tsx
> +  children: ReactNode;
Sure. I didnt see that.

2024-02-16 10:18 UTC, jazztinecruz commented on core/components/typography/index.tsx
> +"use client";
Done!

2024-02-16 10:19 UTC, jazztinecruz commented on core/components/button/index.tsx
Resolved

2024-02-16 10:19 UTC, jazztinecruz commented on core/components/language/index.tsx
> +"use client";
Resolved!

2024-02-16 10:19 UTC, jazztinecruz commented on core/components/icon/index.tsx
> +  Svg: React.ForwardRefExoticComponent<
Done!

2024-02-26 13:49 UTC, nikkoabucejo approved these changes
LGTM

2024-02-26 17:12 UTC, merged